language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
    - docker

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
    - cmake
    - qttools5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - libqt5qml5
    - doxygen

before_install:
    - sudo apt-get install -qq qt5-default qttools5-dev-tools libqt5opengl5-dev

before_script:
    - mkdir build
    - cd build
    - cmake ../

script:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
    - make

before_deploy:
    - make package

notifications:
  on_success: change
  on_failure: always

deploy:
  provider: releases
  api_key:
    secure: kIX221nPUe3OM5CNeEJ1iyRg2FFpmlL7c+uxJS11+HBRcFTGCIArHoxMIUb1u289+Co0jp42BVxhpo9PaKhHhzy3iVsKM1xOty3GAr9/1KzVnvJY0dOWqO2cYks4w24WF50ii3kUtYGVKpJrsHPT8UeI2z+taYr1jBmKkoYuoWDG+3CAZytLAsOVDRPylhzSD8B+OrCHIbN1npcitEpFUMJWgvDVi6ZKsz8o6obs/NhwFEc9TBDhS7CeIoAcNt7S0WdDM4ZyHyOeYShWxL0DlZBuhvS7SVZbxy/DS/cTAyoaWqgFLQokmhsKkVIytnq40kC9kGUZvoSpfwtfnA55eElFP5sNbnjQEUaDgq8Doi+aTTc7WRmhBCJbmz6RlqPAECQzx67JuTukV7F6Ds6B34+9naV3dAhj7dnMAoIvY1UK4NhvT+w3aQNR3B93TLZfYHvAmVoZcMGEY/EqLbHdMdJ7E9YGEQQUXW/753EmulCu9/O/gEs+8DlNc1ejFUGJhQmTyJBOLupJpFanC+6mTcbSGlJLwAHxL5yuJ0x5xLzZvJ9jTJI1QFu8ZztFw6gPCBpxPVle6E/Ht3CIByoK5RtKzhJBxgYDG+k0Yaqgbp1wh1ET56xEj8GxQlTKW43Mwbt4aXAarZ11C3erab5lCQyubIUXuq0TWxJLDTfOC6I=
  file:
    - packages/OpenHantek-Release.sh
    - packages/OpenHantek-Release.zip
  on:
    repo: OpenHantek/openhantek
