language: cpp
compiler: gcc
sudo: required
services:
    - docker

addons:
  apt:
    packages:
    - cmake
    - qttools5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - libqt5qml5
    - doxygen

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools

before_script:
    - cd openhantek
    - qmake

script: make

notifications:
    on_success: change
    on_failure: always