platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

clone_folder: C:\projects\openhantek

install:
#  - cinst cmake
  
image:
  - Visual Studio 2015

shallow_clone: true

before_build:
  - if [%PLATFORM%] == [x64] set QT5=C:\Qt\5.8\msvc2015_64
  - if [%PLATFORM%] == [x64] set VSARCH=x86
  - if [%PLATFORM%] == [x64] set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64"
  - if [%PLATFORM%] == [Win32] set QT5=C:\Qt\5.8\msvc2015
  - if [%PLATFORM%] == [Win32] set VSARCH=x64
  - if [%PLATFORM%] == [Win32] set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015"
  - set Path=%QT5%\bin;%Path%
  - md build
  - cd build
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %VSARCH%
  - cmake.exe -G "%CMAKE_GENERATOR_NAME%" "-DCMAKE_PREFIX_PATH=%QT5%" -DCMAKE_BUILD_TYPE=%configuration% ..
  
build:

build_script:
  - cmake --build . --config Release --target package

artifacts:

  - path: build\openhantek\$(configuration)
    name: OpenHantek_jt-$(platform)-b$(APPVEYOR_BUILD_NUMBER)
    type: zip

  - path: build\packages\*.exe
    name: installer

# User "ci-openhantek". Uses a appveyor encrypted github access token for that user.
deploy:
  - provider: GitHub
    artifact: OpenHantek_jt-$(platform)-b$(APPVEYOR_BUILD_NUMBER)
    release: OpenHantek_jt-$(platform)-b$(APPVEYOR_BUILD_NUMBER)
    description: 'OpenHantek Windows Build (ZIP)'    
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: p5VWPfJhLhTNBBjEGnJaSbbhtFSjlWRZRABrrXbuPeo62x8iN1YpU8jah4hnSYlg
    on:
      branch: master                # release from master branch only
#      appveyor_repo_tag: true       # deploy on tag push only

#notifications:
#  - provider: Email
#    to:
#      - user1@email.com
#    on_build_status_changed: true
